### ISSUE TITLE
docker compose with folder with models

### ISSUE THREAD

**Issue by shuther** [michaelfeil/infinity#215]
### Feature request

1. Allow the models to be picked up from/downloaded into a folder.
2. Propose a maintained docker compose with this implementation (this folder should be mapped to the host)
3. Propose some curl examples to call the API
I am confused by HF_HOME, --model-name-or-path but it already exists

### Motivation

Maintenance of the model library would be easier if the models would not be part of the Docker (save space and restart)

### Your contribution

difficult for now

**Comment by michaelfeil** [comment]
Thanks for the feedback. I'll consider a docker run command that maps the huggingface cache and adjacent files. The download should however be managed by infinity. 

I don't think docker-compose is a contemporary good approach, and I am rejecting to maintain a docker-compose for now, until I see very good arguments. I'd rather have a k8s template.

**Comment by polyyarp** [comment]
Hi @michaelfeil ,

I also curious how to implement infinity using docker compose. I understand you don't want to maintain it. But can you give examples on how to use it on docker compose file?

For example, here is my command for docker run:
```
port=7997
model1=dunzhang/stella_en_1.5B_v5
volume=$PWD/data
engine=torch
device=cuda
dtype=float32

docker run -it --gpus all \
 -v $volume:/app/.cache \
 -p $port:$port \
 michaelf34/infinity:0.0.73 \
 v2 \
 --model-id $model1 \
 --port $port \
 --engine $engine \
 --device $device \
 --dtype $dtype 
```

when I convert to docker-compose.yml, it looks like this:
```
services:
pvg.localembedding:
    image: michaelf34/infinity:0.0.73
    environment:
      - INFINITY_MODEL_ID=${INFINITY_MODEL_ID}
      - INFINITY_PORT=${INFINITY_PORT}
      - INFINITY_ENGINE=${INFINITY_ENGINE}
      - INFINITY_DEVICE=${INFINITY_DEVICE}
      - INFINITY_DTYPE=${INFINITY_DTYPE}
    ports:
      - 4007:4007
    volumes:
      - ./pvg.localembedding:/app
    command: infinity_emb v2
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    stdin_open: true
    tty: true
```

But the error says:
```bash
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "infinity_emb": executable file not found in $PATH: unknown
```

Can you help me point out which one causing this issue?

**Comment by gururaser** [comment]
@polyyarp Hi, 

This one works for me:

```
services:
  infinity:
    image: michaelf34/infinity:latest-cpu
    ports:
      - "7997:7997"
    environment:
      - INFINITY_MODEL_ID=BAAI/bge-m3
      - INFINITY_PORT=7997
      - INFINITY_ENGINE=optimum
      - INFINITY_DEVICE=cpu
    volumes:
      - ./data:/app/.cache
    command: >
      v2
      --model-id BAAI/bge-m3
      --port 7997
      --engine optimum
      --device cpu
```

```
2025-02-15 03:37:58 INFO:     Uvicorn running on http://0.0.0.0:7997 (Press CTRL+C to quit)
2025-02-15 03:38:24 INFO:     172.21.0.1:60026 - "GET /docs HTTP/1.1" 200 OK
2025-02-15 03:38:24 INFO:     172.21.0.1:60026 - "GET /openapi.json HTTP/1.1" 200 OK
2025-02-15 03:39:16 INFO:     172.21.0.1:39892 - "GET /models HTTP/1.1" 200 OK
2025-02-15 03:39:33 INFO:     172.21.0.1:57498 - "POST /embeddings HTTP/1.1" 200 OK
2025-02-15 03:39:36 INFO:     172.21.0.1:57498 - "POST /embeddings HTTP/1.1" 200 OK
```

Well I just discovered Infinity like 30 minutes ago. That's why I don't know the details
